server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: workerModule
          uri: http://localhost:8001/
          predicates:
            - Path=/workers/**
        - id: payrollModule
          uri: http://localhost:8101/
          predicates:
            - Path=/payments/**

