server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: http://localhost:8001/
          predicates:
            - Path=hr-worker/workers/**
        - id: hr-payroll
          uri: http://localhost:8101/
          predicates:
            - Path=hr-payroll/payments/**
        - id: hr-user
          uri: http://localhost:8102/
          predicates:
            - Path=hr-user/users/**
        - id : hr-oauth
          uri: http://localhost:8002/
          predicates:
            - Path=hr-oauth/users/**

