server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: http://localhost:8001/
          predicates:
            - Path=/workers/**
        - id: hr-payroll
          uri: http://localhost:8101/
          predicates:
            - Path=/payments/**

